# project_id = "gxhmxupwkmdkojctezlu"

[functions.referral]
verify_jwt = false

[functions.send-premium-push]
verify_jwt = false

[functions.zawodtyper-proxy]
verify_jwt = false

[functions.ai-analyze]
verify_jwt = false
