create table if not exists public.push_tokens (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  token text not null unique,
  platform text not null,
  enabled boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

alter table public.push_tokens enable row level security;

drop policy if exists "push_tokens_select_own" on public.push_tokens;
create policy "push_tokens_select_own"
on public.push_tokens
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "push_tokens_insert_premium" on public.push_tokens;
create policy "push_tokens_insert_premium"
on public.push_tokens
for insert
to authenticated
with check (
  auth.uid() = user_id
  and exists (
    select 1
    from public.premium_access pa
    where pa.user_id = auth.uid()
      and pa.expires_at > now()
  )
);

drop policy if exists "push_tokens_update_premium" on public.push_tokens;
create policy "push_tokens_update_premium"
on public.push_tokens
for update
to authenticated
using (
  auth.uid() = user_id
  and exists (
    select 1
    from public.premium_access pa
    where pa.user_id = auth.uid()
      and pa.expires_at > now()
  )
)
with check (
  auth.uid() = user_id
  and exists (
    select 1
    from public.premium_access pa
    where pa.user_id = auth.uid()
      and pa.expires_at > now()
  )
);

drop policy if exists "push_tokens_delete_own" on public.push_tokens;
create policy "push_tokens_delete_own"
on public.push_tokens
for delete
to authenticated
using (auth.uid() = user_id);

